spring:
  profiles:
    active: dev  
server:
  port: 8888
---
spring:
  profiles: dev
  application:
    name: MICROSVERICE-USER-DEV
---
spring:
  profiles: test
  application:
    name: MICROSVERICE-USER-TEST
